Group.destroy_all
Exercise.destroy_all

["Abs", "Arms", "Back", "Chest", "Legs"].each do |group|
  Group.create!(name: group)
end
#abs
abs = Group.where(:name => 'Abs').first
Exercise.create(name: 'Bicycle', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Captains Chair', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Ball Crunch', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Vertical Leg Crunch', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Ab Roll', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Long Arm Crunch', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Reverse Crunch', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Crunch With Heel Push', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Plank', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Oblique Crunches', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Reverse Crunches', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Jackknife Crunch', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Knee Tucks', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Wood Chops', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'The Side Crunch', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'The Prone Plank', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'The Cobra', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'The Hundred', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Squat Thrust with Twist', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Abdominal Hold', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)

#arms
arms = Group.where(:name => 'Arms').first
Exercise.create(name: 'Biceps Curl', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Dumbbell Overhead Triceps Extension', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Dumbell Bench Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Triceps Kickback', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Standing Dumbbell Overhead Triceps Extension', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Triceps Pushdown', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Bent Knee Push-up', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Downward-facing Dog', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Bodyweight Dips', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Overhead Triceps Stretch', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Partner Standing Row with Resistance Tubing', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Single Arm Barbell Jammer', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Standing Shoulder Extension', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Triceps Extension with Tubing', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Atomic Push-up', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Back Row', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Dumbbell Hammer Curl', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Barbell Bench Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Barbell Bent-over Row', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Barbell Push Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Chin-ups', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Decline Barbell Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Dumbbell Preacher Curl', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Standing Dumbbell Overhead Triceps Extension', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Triceps Pushdown', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Bodyweight Dips', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Seated Dumbbell Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)

#back
back = Group.where(:name => 'Back').first
Exercise.create(name: 'Deadlift', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Pullup', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Back Raise', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Scapula Pulldown', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Inverted Row', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Lat Pulldown', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Scapula Pulldown', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Barbell Shrug', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Back Raise', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Face Pull', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Back Extension', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Barbell, Overhand', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Cable, Single Arm, Overhand Grip', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Cable, Straight Bar', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Dumbbell', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Alternating, Reverse Grip', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Kneeling, Reverse Grip', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Dumbbell, Reverse Grip', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Cable Rows, Seated', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Cable Rows, Seated, Bar, Underhand Grip', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Hip Extensions, Bridge', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row with Static Hold, Dumbbell', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Barbell, Reverse Grip', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Hug Knees To Chest', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Hyperextensions (Back Extensions)', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: '', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)

back = Group.where(:name => 'Chest').first
Exercise.create(name: 'Bench Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Cable Chest Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Butterfly', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Cable Crossover', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Chest And Front Of Shoulder Stretch', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Chest Push', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Decline Barbell Bench Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Chest Stretch on Stability Ball', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Decline Dumbbell Bench Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Decline Dumbbell Flyes', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Decline Push-Up', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Dips - Chest Version', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Downward Facing Balance', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Drop Push', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Dumbbell Bench Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Dynamic Chest Stretch', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Elbows Back', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Flat Bench Cable Flyes', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Forward Drag with Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Heavy Bag Thrust', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Incline Cable Flye', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)

back = Group.where(:name => 'Legs').first
Exercise.create(name: 'Leg Extension', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'One-at-a-Time Leg Extension', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Seated Leg Curl', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Prone Leg Curl', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'One-at-a-Time Prone Leg Curl', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Leg Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Incline Leg Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Squat', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Seated Hip Adduction', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Standing Hip Adduction', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Standing Hip Adduction using Low Pulley', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Seated Hip Abduction', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Standing Hip Abduction', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Standing Hip Abduction using Low Pulley', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Calf Raise on Calf Bench', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Calf Raise on Leg Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'High Calf Raise on Universal Leg Machine', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Low Calf Raise on Universal Leg Machine', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Side Step Squats', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Front One-Legged Squat', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Step Ups', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'One-Legged Deadlift', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Knee Deadlift', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Lunge on the Ball', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Sliding Side Lunge', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Lunge Sweep', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Hip Extensions', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Ball Butt Lift', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Hamstring Rolls', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
