Group.destroy_all
Exercise.destroy_all

["Abs", "Arms", "Back", "Chest", "Legs"].each do |group|
  Group.create!(name: group)
end
#abs
abs = Group.where(:name => 'Abs')
Exercise.create(name: 'Bicycle', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Captains Chair', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Ball Crunch', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Vertical Leg Crunch', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Ab Roll', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Long Arm Crunch', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Reverse Crunch', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Crunch With Heel Push', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Plank', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Oblique Crunches', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Reverse Crunches', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Jackknife Crunch', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Knee Tucks', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Wood Chops', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'The Side Crunch', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'The Prone Plank', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'The Cobra', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'The Hundred', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Squat Thrust with Twist', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)
Exercise.create(name: 'Abdominal Hold', description: 'Some sort of description about the exercise.  You know it really is a description', group: abs)

#arms
arms = Group.where(:name => 'Arms')
Exercise.create(name: 'Biceps Curl', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Dumbbell Overhead Triceps Extension', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Dumbell Bench Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Triceps Kickback', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Standing Dumbbell Overhead Triceps Extension', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Triceps Pushdown', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Bent Knee Push-up', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Downward-facing Dog', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Bodyweight Dips', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Overhead Triceps Stretch', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Partner Standing Row with Resistance Tubing', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Single Arm Barbell Jammer', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Standing Shoulder Extension', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Triceps Extension with Tubing', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Atomic Push-up', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Back Row', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Dumbbell Hammer Curl', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Barbell Bench Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Barbell Bent-over Row', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Barbell Push Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Chin-ups', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Decline Barbell Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Dumbbell Preacher Curl', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Standing Dumbbell Overhead Triceps Extension', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Triceps Pushdown', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Bodyweight Dips', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)
Exercise.create(name: 'Seated Dumbbell Press', description: 'Some sort of description about the exercise.  You know it really is a description', group: arms)

#back
back = Group.where(:name => 'Back')
Exercise.create(name: 'Deadlift', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Pullup', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Back Raise', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Scapula Pulldown', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Inverted Row', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Lat Pulldown', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Scapula Pulldown', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Barbell Shrug', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Back Raise', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Face Pull', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Back Extension', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Barbell, Overhand', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Cable, Single Arm, Overhand Grip', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Cable, Straight Bar', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Dumbbell', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Dumbbell, Alternating, Reverse Grip', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Dumbbell, Kneeling, Reverse Grip', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Dumbbell, Reverse Grip', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Cable Rows, Seated', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Cable Rows, Seated, Bar, Underhand Grip', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Hip Extensions, Bridge', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row with Static Hold, Dumbbell', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: 'Bent Over Row, Barbell, Reverse Grip', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: '', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: '', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)
Exercise.create(name: '', description: 'Some sort of description about the exercise.  You know it really is a description', group: back)

